### PR TITLE
Add style prop to ScrollView, as already available for View

### PR DESCRIPTION
**Pull request by mcallisto**
For now I have added only the `style` prop.

Please let me know if the other inherited props from `View`, see
https://facebook.github.io/react-native/docs/scrollview
must be added as well. And, if yes, if there is a better and drier way than just copy paste.

### CODE REVIEW

**Comment by shadaj** [comment]
@mcallisto thanks for the PR! Yeah, it would be great to add the other inherited props too. Unfortunately, there's no way to merge the properties of two case classes together into a new case class so everything will just have to be copied over.

**Comment by mcallisto** [comment]
> so everything will just have to be copied over.

Done, thank you @shadaj

**Comment by mcallisto** [comment]
Formatted, updated changelog and tried to rebase, but probably messed this last part.
It this PR is unusable, as I fear, just let me know: I will close this and put evrything in a new one.

**Comment by shadaj** [comment]
Yeah, probably needs a history rewrite (either within this PR or a new one). Perhaps just cherry-picking the original commits onto the latest master would work?

**Pull request closed without merging**
