### PR TITLE
Add syntactic sugar for capture phase handlers, such as 'onKeyDownCapture'

### PR DESCRIPTION
**Pull request by strobe**
To address the #689 .

Add most of capture phase handlers described here:
https://react.dev/reference/react-dom/components/common

As result following and similar handlers would be supported:

```scala
input(onKeyUpCapture := (event => { println("onKeyUpCapture") }))
input(onKeyPressCapture := (event => { println("onKeyPressCapture") }))
input(onKeyDownCapture := (event => { println("onKeyDownCapture") }))
```

However it's doesn't cover 'onBeforeInput' mention in #689 .

List of added handlers:
  
  - onCopyCapture
  - onCutCapture
  - onPasteCapture
  - onCompositionEndCapture
  - onCompositionStartCapture
  - onCompositionUpdateCapture
  - onKeyDownCapture
  - onKeyPressCapture
  - onKeyUpCapture
  - onFocusCapture
  - onBlurCapture
  - onSubmitCapture
  - onClickCapture
  - onContextMenuCapture
  - onDoubleClickCapture
  - onDragCapture
  - onDragEndCapture
  - onDragEnterCapture
  - onDragOverCapture
  - onDragStartCapture
  - onDropCapture
  - onMouseDownCapture
  - onMouseOutCapture
  - onMouseUpCapture
  - onPointerDownCapture
  - onPointerUpCapture
  - onPointerCancelCapture
  - onPointerOutCapture
  - onSelectCapture
  - onTouchCancelCapture
  - onTouchEndCapture
  - onTouchMoveCapture
  - onTouchStartCapture
  - onScrollCapture
  - onWheelCapture
  - onAbortCapture
  - onCanPlayCapture
  - onCanPlayThroughCapture
  - onDurationChangeCapture
  - onEmptiedCapture
  - onEncryptedCapture
  - onEndedCapture
  - onErrorCapture
  - onLoadedDataCapture
  - onLoadedMetadataCapture
  - onLoadStartCapture
  - onPauseCapture
  - onPlayCapture
  - onPlayingCapture
  - onProgressCapture
  - onRateChangeCapture
  - onSeekedCapture
  - onSeekingCapture
  - onStalledCapture
  - onSuspendCapture
  - onTimeUpdateCapture
  - onVolumeChangeCapture
  - onWaitingCapture
  - onLoadCapture
  - onAnimationStartCapture
  - onAnimationEndCapture
  - onAnimationIterationCapture
  - onToggleCapture
  - onCloseCapture

### CODE REVIEW

**Comment by shadaj** [comment]
I'm wondering if it would be better to have an optional field on events to mark if they have a capture variant. So rather than treating them as completely separate properties we can generate the variant when that is enabled?

**Comment by strobe** [comment]
do you mean something like this?
```diff
    {
      "attributeName" : "onKeyDown",
      "attributeType" : "KeyboardEventHandler",
      "docLines" : [
        ""
      ],
+     "hasCaptureVariant" : true, 
      "compatibleTags" : null,
      "withDash" : false
    },
```
I guess that could save some time of editing 'web/html.json' but not sure about other benefits.

If you think that it would work better, I'll update PR to make it work in such way.

**Comment by shadaj** [comment]
Yeah that's exactly what I'm thinking. The main benefit I see is if types change in the future we don't have to worry about keeping things in sync.

**Comment by strobe** [comment]
@shadaj updated code, now has everything as 'hasCaptureVariant' option

**Review by shadaj — APPROVED** [review]
This is great, thanks for the PR!

**Comment by strobe** [comment]
great, I will update #696 accordingly somewhere on next week

**Pull request merged**
